Update to Dioxus 0.5.1 and code cleanup
saicu/dioxus-helmet pull request #5
Opened 2024-07-05 15:13 UTC by samu698

I updated the code for Dioxus 0.5.1 and cleaned the code.
I rewrote nested if let as let else, updated the dependencies.

There is a functional change: the `data-helment-id` was removed Elements are tracked using the mounted_element field of ElementMap, this removes the need to query the dom to search the Elements to remove.

Closes #3

2024-07-07 11:42 UTC, marc2332 requested changes
Nice, but you should also adapt the example from the README.md

2024-07-07 11:43 UTC, samu698 commented
> Nice, but you should also adapt the example from the README.md

Will do

2024-07-07 11:53 UTC, samu698 commented
Sorry for the request I clicked by accident 🤦

2024-07-11 12:50 UTC, samu698 commented
Sorry to bother, I fixed the readme issue, is the PR ready to be merged or it still has issues

2024-09-07 22:31 UTC, merged